import { Category, ThemeType, LanguageType } from './types';

export const DEFAULT_CATEGORIES: Category[] = [
  { id: '1', name: 'Dry Fruits', icon: '🥜' },
  { id: '2', name: 'Masala', icon: '🌶️' },
  { id: '3', name: 'Spices', icon: '🌿' },
  { id: '4', name: 'Seeds', icon: '🌻' },
  { id: '5', name: 'Pulses', icon: '🫘' },
  { id: '6', name: 'Others', icon: '📦' },
];

export const UNITS = [
  { label: 'Weight', values: ['KG', 'Gram', '250gm', 'MG', 'Chatak', 'Tola', 'Quintal', 'Ton', 'Pound'] },
  { label: 'Packaging', values: ['Packet', 'Box', 'Bag', 'Pouch', 'Sack', 'Jar', 'Bottle', 'Tin', 'Can', 'Carton', 'Crate'] },
  { label: 'Quantity', values: ['Piece', 'Dozen', 'Bundle', 'Set', 'Pair', 'Unit'] },
];

export const THEMES: { id: ThemeType; name: string; description: string; emoji: string }[] = [
  { id: 'ultra_premium', name: 'Ultra Premium', description: 'Advanced aesthetics, smooth slow-mo aurora, high clarity', emoji: '🔮' },
  { id: 'midnight_blue', name: 'Midnight Pro', description: 'Deep contrast, technical precision', emoji: '🌑' },
  { id: 'neo_brutalist', name: 'Neo-Brutalist', description: 'Bold, graphic colors and energy', emoji: '⚡' },
  { id: 'glass_modern', name: 'Glass Morphic', description: 'Immersive frosted glass layers', emoji: '✨' },
  { id: 'luxury_gold', name: 'Luxury Gold', description: 'Premium, elegant gold accents', emoji: '👑' },
  { id: 'premium_dynamic', name: 'Premium Dynamic', description: 'luxurious, smooth animated gradients', emoji: '💎' },
  { id: 'emerald_matrix', name: 'Technical Green', description: 'Matrix data-grid optimization', emoji: '📟' },
];

export const LANGUAGES: { id: LanguageType; name: string; label: string; emoji: string }[] = [
  { id: 'en', name: 'English (US)', label: 'Professional English', emoji: '🇬🇧' },
  { id: 'hi-en', name: 'Hinglish (Mix)', label: 'Hindi + English', emoji: '🇮🇳' },
  { id: 'hi', name: 'हिन्दी (शुद्ध)', label: 'Pure Hindi', emoji: '🇮🇳' },
  { id: 'mr', name: 'मराठी (अस्सल)', label: 'Authentic Marathi', emoji: '🇮🇳' },
];

export const UI_TEXT = {
  en: {
    inventory: 'Unified Inventory',
    search: 'Lookup items, units, or categories...',
    totalItems: 'Node Count',
    totalValue: 'Cumulative Asset Value',
    categories: 'Sector Classification',
    buy: 'Cost Basis',
    wholesale: 'Tier-2 Pricing',
    retail: 'Tier-1 Revenue',
    addItem: 'Initialize New Asset',
    editItem: 'Modify Data Entry',
    save: 'Commit Changes',
    cancel: 'Abort',
    delete: 'Purge Record',
    settings: 'Core Configuration',
    theme: 'UI Visual Deck',
    language: 'Linguistic Interface',
    locked: 'Encrypted',
    unlocked: 'Access Granted',
    enterPin: 'Verification Required',
    createPin: 'Generate Security Key',
    confirmPin: 'Re-verify Key',
    stats: 'Analytics', 
    profile: 'Operator Profile',
    all: 'Global',
    unit: 'Metric',
    quantity: 'Asset Volume',
    buyingPrice: 'Acquisition Cost',
    wholesalePrice: 'Wholesale Vector',
    retailPrice: 'Consumer Retail',
    margin: 'Profit Spread',
    applyMargin: 'Auto-Calibrate',
    notes: 'Internal Log',
    emptyList: 'Registry Empty. System standing by...',
    notesDashboard: 'Notes & Reminders',
    addNote: 'Record New Entry',
    viewAllNotes: 'Expand Log',
    recentPriceChanges: 'Price Volatility Feed',
    login: 'Operator Authorization',
    logout: 'Terminate Session',
    aiInsight: 'AI Business Insight',
    analyze: 'Analyze',
    analyzing: 'Generating...',
    getAiAdvice: 'Get AI-powered pricing strategy & business tips.',
    lastCheck: 'Last Check',
    updateRecord: 'Update record',
    newEntry: 'New entry',
    identityParams: 'Identity parameters',
    financialConfig: 'Financial configuration',
    operationalNotes: 'Operational notes',
    stockStatus: 'Stock Status',
    lowStock: 'Low Stock Alert',
    installApp: 'Deploy Pro Node',
    installDesc: 'Install to home screen for native access',
    clientShare: 'Client Share',
    broadcast: 'Broadcast via WhatsApp',
    dataEngine: 'Data Engine',
    backupExport: 'Backup & Cloud Export',
    systemCore: 'System Core',
    exportVectors: 'Export Vectors',
    exportExcel: 'Export Data to Excel',
    exportPdf: 'Export Data to PDF',
    backupInfra: 'Backup Infrastructure',
    backupNow: 'Backup System Now',
    restoreBackup: 'Restore Backup',
    maintenanceCore: 'Maintenance Core',
    importData: 'Import External Data',
    clearCache: 'Clear Local Cache',
    systemInfra: 'System Infrastructure',
    metricPrecision: 'Metric Precision',
    typographyDeck: 'Typography Deck',
    error: 'Error',
    success: 'Success',
    deleteConfirm: 'Delete this item?',
    restoreConfirm: 'Restoring will overwrite current data. Proceed?',
    themeDeck: 'UI Visual Deck',
    accentOverlay: 'Brand Accent Overlay',
    securityCloud: 'Security & Cloud',
    securityKey: 'Security Verification Key',
    costProtection: 'Financial cost protection layer',
    cloudSync: 'Cloud Synchronization',
    firebaseSync: 'Auto-sync with Google Firebase',
    autoStealth: 'Automated Stealth',
    stealthDesc: 'Engage masking protocols on start',
    dataLifecycle: 'Data Lifecycle Management',
    authorization: 'Authorization',
    architecture: 'Architecture',
    liveNode: 'Live Operator Instance',
    localSandbox: 'Local Sandbox Environment',
    terminateSession: 'Terminate Session',
    cloudEntry: 'Cloud Entry',
    compare: 'Compare',
    items: 'Items',
    selected: 'Selected',
    sideBySide: 'Side-by-side analysis',
    compareReady: 'Ready for comparison',
    clear: 'Clear',
    lastChanged: 'Last Updated',
    help: 'Help & Knowledge Base',
    onboardingTitle: 'Welcome to Unified Inventory!',
    onboardingSub: 'Let’s set up your store in 30 seconds.',
    tourNext: 'Next Feature',
    tourFinish: 'Start Managing',
    tourSkip: 'Skip Tour',
    step1Title: 'Inventory Dashboard',
    step1Desc: 'Manage your entire stock here. Use search to find items instantly.',
    step2Title: 'Global Search',
    step2Desc: 'Find products by English, Hindi, or Hinglish names.',
    step3Title: 'Analytics & Value',
    step3Desc: 'Track your total asset value and profit margins in real-time.',
    faq1Q: 'How to backup data?',
    faq1A: 'Enable "Cloud Synchronization" in settings to auto-sync with Google Firebase.',
    faq2Q: 'Can I use this offline?',
    faq2A: 'Yes, it works offline as a PWA. Data syncs when you go back online.',
  },
  hi: {
    inventory: 'इनवेंटरी मैनेजमेंट',
    search: 'आइटम या श्रेणी ढूंढें...',
    totalItems: 'कुल स्टॉक संख्या',
    totalValue: 'कुल संपत्ति मूल्य',
    categories: 'वर्गीकरण',
    buy: 'लागत मूल्य',
    wholesale: 'थोक दर',
    retail: 'खुदरा दर',
    addItem: 'नया स्टॉक जोड़ें',
    editItem: 'विवरण बदलें',
    save: 'डेटा सुरक्षित करें',
    cancel: 'रद्द करें',
    delete: 'डिलीट करें',
    settings: 'सिस्टम सेटिंग्स',
    theme: 'विजुअल थीम',
    language: 'सञ्चालन भाषा',
    locked: 'सुरक्षित (लॉक)',
    unlocked: 'अनलॉक',
    enterPin: 'पिन दर्ज करें',
    createPin: 'सुरक्षा पिन बनाएं',
    confirmPin: 'पिन की पुष्टि',
    stats: 'डेटा विश्लेषण',
    profile: 'यूजर प्रोफाइल',
    all: 'सभी डेटा',
    unit: 'मात्रक (Unit)',
    quantity: 'कुल मात्रा',
    buyingPrice: 'खरीद कीमत',
    wholesalePrice: 'होलसेल कीमत',
    retailPrice: 'रिटेल कीमत',
    margin: 'मुनाफा',
    applyMargin: 'मार्जिन सेट करें',
    notes: 'विशेष टिपण्णी',
    emptyList: 'कोई डेटा नहीं मिला। सिस्टम तैयार है...',
    notesDashboard: 'व्यवसाय लॉग और अनुस्मारक',
    addNote: 'नया नोट लिखें',
    viewAllNotes: 'सभी लॉग देखें',
    recentPriceChanges: 'मूल्य परिवर्तन इतिहास',
    login: 'सिस्टम लॉगिन',
    logout: 'लॉगआउट',
    aiInsight: 'AI व्यापार सलाह',
    analyze: 'विश्लेषण करें',
    analyzing: 'तैयार हो रहा है...',
    getAiAdvice: 'AI-संचालित मूल्य निर्धारण रणनीति और व्यावसायिक सुझाव प्राप्त करें।',
    lastCheck: 'अंतिम जाँच',
    updateRecord: 'रिकॉर्ड अपडेट करें',
    newEntry: 'नई एंट्री',
    identityParams: 'पहचान पैरामीटर',
    financialConfig: 'वित्तीय कॉन्फ़िगरेशन',
    operationalNotes: 'परिचालन नोट्स',
    stockStatus: 'स्टॉक की स्थिति',
    lowStock: 'कम स्टॉक अलर्ट',
    installApp: 'ऐप इंस्टॉल करें',
    installDesc: 'नेटिव एक्सेस के लिए होम स्क्रीन पर जोड़ें',
    clientShare: 'क्लाइंट शेयर',
    broadcast: 'व्हाट्सएप के जरिए भेजें',
    dataEngine: 'डेटा इंजन',
    backupExport: 'बैकअप और क्लाउड एक्सपोर्ट',
    systemCore: 'सिस्टम कोर',
    exportVectors: 'निर्यात (Export)',
    exportExcel: 'एक्सेल में एक्सपोर्ट करें',
    exportPdf: 'PDF में एक्सपोर्ट करें',
    backupInfra: 'बैकअप इंफ्रास्ट्रक्चर',
    backupNow: 'अभी बैकअप लें',
    restoreBackup: 'बैकअप रिस्टोर करें',
    maintenanceCore: 'रखरखाव कोर',
    importData: 'बाहरी डेटा इम्पोर्ट करें',
    clearCache: 'लोकल कैश साफ़ करें',
    systemInfra: 'सिस्टम इंफ्रास्ट्रक्चर',
    metricPrecision: 'परिशुद्धता (Precision)',
    typographyDeck: 'फ़ॉन्ट साइज',
    error: 'त्रुटि',
    success: 'सफलता',
    deleteConfirm: 'क्या आप इसे हटाना चाहते हैं?',
    restoreConfirm: 'रिस्टोर करने से वर्तमान डेटा बदल जाएगा। क्या आप जारी रखना चाहते हैं?',
    themeDeck: 'विजुअल डेक',
    accentOverlay: 'ब्रांड एक्सेंट ओवरले',
    securityCloud: 'सुरक्षा और क्लाउड',
    securityKey: 'सुरक्षा वेरिफिकेशन पिन',
    costProtection: 'वित्तीय सुरक्षा परत',
    cloudSync: 'क्लाउड सिंक्रोनाइज़ेशन',
    firebaseSync: 'गूगल फायरबेस के साथ सिंक',
    autoStealth: 'स्वचालित गोपनीयता (Stealth)',
    stealthDesc: 'शुरुआत में लागत छुपाएं',
    dataLifecycle: 'डेटा जीवनचक्र प्रबंधन',
    authorization: 'प्राधिकरण',
    architecture: 'आर्किटेक्चर',
    liveNode: 'लाइव ऑपरेटर इंस्टेंस',
    localSandbox: 'लोकल सैंडबॉक्स वातावरण',
    terminateSession: 'सत्र समाप्त करें',
    cloudEntry: 'क्लाउड एंट्री',
    compare: 'तुलना करें',
    items: 'आइटम',
    selected: 'चुने गए',
    sideBySide: 'एक साथ तुलना',
    compareReady: 'तुलना के लिए तैयार',
    clear: 'साफ करें',
    lastChanged: 'अंतिम अपडेट',
    help: 'मदद और जानकारी',
    onboardingTitle: 'आपका स्वागत है!',
    onboardingSub: 'चलिए 30 सेकंड में सेटअप करते हैं।',
    tourNext: 'अगला',
    tourFinish: 'शुरू करें',
    tourSkip: 'छोड़ें',
    step1Title: 'स्टॉक डैशबोर्ड',
    step1Desc: 'अपना सारा स्टॉक यहाँ मैनेज करें।',
    step2Title: 'सर्च',
    step2Desc: 'किसी भी भाषा में सामान ढूंढें।',
    step3Title: 'एनालिटिक्स',
    step3Desc: 'अपना कुल मुनाफा और वैल्यू यहाँ देखें।',
  },
  mr: {
    inventory: 'मालमत्ता व्यवस्थापन',
    search: 'वस्तू किंवा श्रेणी शोधा...',
    totalItems: 'एकूण संख्या',
    totalValue: 'एकूण मालमत्ता मूल्य',
    categories: 'वर्गवारी',
    buy: 'मूळ किंमत',
    wholesale: 'घाऊक दर',
    retail: 'किरकोळ दर',
    addItem: 'नवीन नोंद करा',
    editItem: 'नोंद सुधारित करा',
    save: 'बदल जतन करा',
    cancel: 'रद्द करा',
    delete: 'कायमचे हटवा',
    settings: 'मुख्य सेटिंग्ज',
    theme: 'दृश्य स्वरूप',
    language: 'संवाद भाषा',
    locked: 'सुरक्षित',
    unlocked: 'प्रवेश खुला',
    enterPin: 'पिन टाका',
    createPin: 'सुरक्षा पिन तयार करा',
    confirmPin: 'पिनची पडताळणी',
    stats: 'आकडेवारी',
    profile: 'वापरकर्ता प्रोफाइल',
    all: 'सर्व नोंदी',
    unit: 'परिमाण (Unit)',
    quantity: 'एकूण प्रमाण',
    buyingPrice: 'खरेदी दर',
    wholesalePrice: 'घाऊक दर',
    retailPrice: 'रिटेल दर',
    margin: 'नफा',
    applyMargin: 'मार्जिन लावा',
    notes: 'महत्त्वाची नोंद',
    emptyList: 'काहीही आढळले नाही. सिस्टीम सज्ज आहे...',
    notesDashboard: 'व्यवसाय टीपा आणि आठवण',
    addNote: 'नवीन टीप जोडा',
    viewAllNotes: 'सर्व पहा',
    recentPriceChanges: 'दर बदल फीड',
    login: 'प्रवेश करा',
    logout: 'बाहेर पडा',
    aiInsight: 'AI व्यावसायिक सल्ला',
    analyze: 'विश्लेषण करा',
    analyzing: 'तयार होत आहे...',
    getAiAdvice: 'AI-आधारित किंमत धोरण आणि व्यवसाय टिपा मिळवा.',
    lastCheck: 'शेवटची तपासणी',
    updateRecord: 'नोंद अपडेट करा',
    newEntry: 'नवीन एन्ट्री',
    identityParams: 'ओळख पॅरामीटर्स',
    financialConfig: 'आर्थिक कॉन्फिगरेशन',
    operationalNotes: 'ऑपरेशनल नोट्स',
    stockStatus: 'स्टॉक स्थिती',
    lowStock: 'कमी स्टॉक अलर्ट',
    installApp: 'अ‍ॅप इंस्टॉल करा',
    installDesc: 'वापरासाठी होम स्क्रीनवर जोडा',
    clientShare: 'क्लाइंट शेअर',
    broadcast: 'व्हॉट्सअ‍ॅपद्वारे शेअर करा',
    dataEngine: 'डेटा इंजिन',
    backupExport: 'बॅकअप आणि क्लाउड एक्सपोर्ट',
    systemCore: 'सिस्टम कोअर',
    exportVectors: 'डेटा एक्सपोर्ट',
    exportExcel: 'एक्सेलमध्ये एक्सपोर्ट करा',
    exportPdf: 'PDF मध्ये एक्सपोर्ट करा',
    backupInfra: 'बॅकअप इन्फ्रास्ट्रक्चर',
    backupNow: 'आताच बॅकअप घ्या',
    restoreBackup: 'बॅकअप रिस्टोर करा',
    maintenanceCore: 'मेंटेन्स कोअर',
    importData: 'बाह्य डेटा इम्पोर्ट करा',
    clearCache: 'लोकल कॅश साफ करा',
    systemInfra: 'सिस्टम इन्फ्रास्ट्रक्चर',
    metricPrecision: 'अचूकता (Precision)',
    typographyDeck: 'फॉन्ट आकार',
    error: 'त्रुटि',
    success: 'यश',
    deleteConfirm: 'तुम्ही हे हटवू इच्छिता का?',
    restoreConfirm: 'रिस्टोर केल्याने सध्याचा डेटा बदलला जाईल. पुढे जायचे का?',
    themeDeck: 'विजुअल डेक',
    accentOverlay: 'ब्रँड अ‍ॅक्सेंट ओव्हरले',
    securityCloud: 'सुरक्षा आणि क्लाउड',
    securityKey: 'सुरक्षा पडताळणी पिन',
    costProtection: 'आर्थिक सुरक्षा स्तर',
    cloudSync: 'क्लाउड सिंक्रोनाइझेशन',
    firebaseSync: 'गूगल फायरबेससह सिंक',
    autoStealth: 'स्वयंचलित गोपनीयता',
    stealthDesc: 'सुरुवातीला खरेदी दर लपवा',
    dataLifecycle: 'डेटा लाइफसायकल मॅनेजमेंट',
    authorization: 'प्राधिकरण',
    architecture: 'आर्किटेक्चर',
    liveNode: 'लाईव्ह ऑपरेटर इन्स्टन्स',
    localSandbox: 'लोकल सँडबॉक्स वातावरण',
    terminateSession: 'सत्र समाप्त करा',
    cloudEntry: 'क्लाउड एन्ट्री',
    compare: 'तुलना करा',
    items: 'वस्तू (Items)',
    selected: 'निवडलेले',
    sideBySide: 'तुलनात्मक विश्लेषण',
    compareReady: 'तुलना करण्यासाठी तयार',
    clear: 'साफ करा',
    lastChanged: 'शेवटचे अपडेट',
    help: 'मदत आणि माहिती',
    onboardingTitle: 'तुमचे स्वागत आहे!',
    onboardingSub: 'चला ३० सेकंदात सेटअप करूया.',
    tourNext: 'पुढील',
    tourFinish: 'सुरू करा',
    tourSkip: 'वगळा',
    step1Title: 'स्टॉक डॅशबोर्ड',
    step1Desc: 'तुमचा सर्व स्टॉक येथे व्यवस्थापित करा.',
    step2Title: 'शोध',
    step2Desc: 'कोणत्याही भाषेत वस्तू शोधा.',
    step3Title: 'अ‍ॅनालिटिक्स',
    step3Desc: 'तुमचा एकूण नफा आणि मूल्य येथे पहा.',
  },
  'hi-en': {
    inventory: 'Inventory Dashboard',
    search: 'Search kijiye...',
    totalItems: 'Total Stock',
    totalValue: 'Net Asset Value',
    categories: 'Categories',
    buy: 'Cost Price',
    wholesale: 'Wholesale Price',
    retail: 'Retail Price',
    addItem: 'Naya Item add karein',
    editItem: 'Details update karein',
    save: 'Data Save karein',
    cancel: 'Cancel',
    delete: 'Record Delete karein',
    settings: 'Controls',
    theme: 'App Look',
    language: 'Language Selection',
    locked: 'Locked State',
    unlocked: 'Unlocked',
    enterPin: 'Pin mang raha hai',
    createPin: 'New Pin set karein',
    confirmPin: 'Dobara Pin dalein',
    stats: 'Stats Deck',
    profile: 'User Profile',
    all: 'Full List',
    unit: 'Unit Metric',
    quantity: 'Quantity Status',
    buyingPrice: 'Buying Cost',
    wholesalePrice: 'Wholesale Price',
    retailPrice: 'Retail Price',
    margin: 'Margin Gap',
    applyMargin: 'Auto Margins',
    notes: 'Extra Info',
    emptyList: 'Kuch nahi mila. Ready to add...',
    notesDashboard: 'Business Notes & Reminders',
    addNote: 'Entry Add Karein',
    viewAllNotes: 'Show Everything',
    recentPriceChanges: 'Price History Tracker',
    login: 'Log-In Karein',
    logout: 'Session End',
    aiInsight: 'AI Business Insight',
    analyze: 'Analyze',
    analyzing: 'Calculating...',
    getAiAdvice: 'AI pricing strategy aur business tips ke liye scan karein.',
    lastCheck: 'Last Check',
    updateRecord: 'Update record',
    newEntry: 'New entry',
    identityParams: 'Identify parameters',
    financialConfig: 'Finance settings',
    operationalNotes: 'Notes section',
    stockStatus: 'Stock status',
    lowStock: 'Kam stock ki alert',
    installApp: 'App install karein',
    installDesc: 'Home screen par add karein direct access ke liye',
    clientShare: 'Share with Client',
    broadcast: 'WhatsApp par bhejein',
    dataEngine: 'Data Center',
    backupExport: 'Backup aur Cloud',
    systemCore: 'System Settings',
    exportVectors: 'Export karein',
    exportExcel: 'Excel sheet banayein',
    exportPdf: 'PDF banayein',
    backupInfra: 'Backup Systems',
    backupNow: 'Backup lein',
    restoreBackup: 'Purana data layein',
    maintenanceCore: 'Clean up',
    importData: 'Naya data layein',
    clearCache: 'Cache saaf karein',
    systemInfra: 'Internal logic',
    metricPrecision: 'Calculation precision',
    typographyDeck: 'Font Size adjust karein',
    error: 'Kuch galat hua',
    success: 'Done!',
    deleteConfirm: 'Delete karna hai?',
    restoreConfirm: 'Purana data replace ho jayega. Sure?',
    themeDeck: 'Visual Look',
    accentOverlay: 'Brand Colors',
    securityCloud: 'Security & Backup',
    securityKey: 'Security PIN',
    costProtection: 'Money safety layer',
    cloudSync: 'Cloud Syncing',
    firebaseSync: 'Firebase auto-sync',
    autoStealth: 'Stealth Mode on startup',
    stealthDesc: 'Cost prices hide karein',
    dataLifecycle: 'Data Management',
    authorization: 'Authorization',
    architecture: 'Architecture',
    liveNode: 'Live Instance',
    localSandbox: 'Local Environment',
    terminateSession: 'Session End',
    cloudEntry: 'Cloud Entry',
    compare: 'Compare',
    items: 'Items',
    selected: 'Selected',
    sideBySide: 'Compare items',
    compareReady: 'Compare click karo',
    clear: 'Hatao',
    lastChanged: 'Update hua',
    help: 'Help aur Guide',
    onboardingTitle: 'Unified Inventory mein Swagat hai!',
    onboardingSub: 'Chaliye 30 seconds mein setup karte hain.',
    tourNext: 'Agla Feature',
    tourFinish: 'Shuru karien',
    tourSkip: 'Chhod dein',
    step1Title: 'Inventory Dashboard',
    step1Desc: 'Apna pura stock yahan manage karein.',
    step2Title: 'Easy Search',
    step2Desc: 'English, Hindi ya Hinglish mein items dhundhein.',
    step3Title: 'Analytics',
    step3Desc: 'Total value aur profit margins live dekhein.',
  },
};

export const AURORA_PALETTES = {
  neon_aurora: {
    id: 'neon_aurora' as const,
    name: "Neon Aurora",
    colors: ['#09041a', '#1a0c47', '#320745', '#081d45', '#22083c', '#09041a'],
    nodes: [
      "rgba(168, 85, 247, 0.28)",  // purple-500
      "rgba(99, 102, 241, 0.28)",  // indigo-500
      "rgba(236, 72, 153, 0.22)",  // pink-500
      "rgba(20, 184, 166, 0.22)",  // teal-500
    ],
    emoji: "🌌"
  },
  sunset: {
    id: 'sunset' as const,
    name: "Crimson Sunset",
    colors: ['#150505', '#3c0c1b', '#5c0628', '#451a08', '#260515', '#150505'],
    nodes: [
      "rgba(239, 68, 68, 0.28)",   // red-500
      "rgba(249, 115, 22, 0.28)",  // orange-500
      "rgba(217, 70, 239, 0.22)",  // fuchsia-500
      "rgba(251, 146, 60, 0.22)",  // amber-400
    ],
    emoji: "🌅"
  },
  deep_sea: {
    id: 'deep_sea' as const,
    name: "Abyssal Deep Sea",
    colors: ['#020813', '#051833', '#082b4d', '#0c3a5e', '#031224', '#020813'],
    nodes: [
      "rgba(14, 165, 233, 0.28)",  // sky-500
      "rgba(59, 130, 246, 0.28)",  // blue-500
      "rgba(6, 182, 212, 0.22)",   // cyan-500
      "rgba(20, 184, 166, 0.22)",  // teal-500
    ],
    emoji: "🌊"
  },
  matrix: {
    id: 'matrix' as const,
    name: "Digital Matrix",
    colors: ['#020d04', '#06200a', '#0c3814', '#051808', '#0b2e10', '#020d04'],
    nodes: [
      "rgba(34, 197, 94, 0.28)",   // green-500
      "rgba(16, 185, 129, 0.28)",  // emerald-500
      "rgba(132, 204, 22, 0.22)",  // lime-500
      "rgba(20, 184, 166, 0.22)",  // teal-500
    ],
    emoji: "🟢"
  },
  cosmic_orchid: {
    id: 'cosmic_orchid' as const,
    name: "Cosmic Orchid",
    colors: ['#0c0213', '#200533', '#3a084d', '#1b0c5e', '#120324', '#0c0213'],
    nodes: [
      "rgba(217, 70, 239, 0.28)",  // fuchsia-500
      "rgba(168, 85, 247, 0.28)",  // purple-500
      "rgba(244, 63, 94, 0.22)",   // rose-500
      "rgba(129, 140, 248, 0.22)", // indigo-400
    ],
    emoji: "🌸"
  },
  cyberpunk_gold: {
    id: 'cyberpunk_gold' as const,
    name: "Cyberpunk Gold",
    colors: ['#120e02', '#2c1e05', '#452b08', '#381603', '#241a02', '#120e02'],
    nodes: [
      "rgba(234, 179, 8, 0.28)",   // yellow-500
      "rgba(245, 158, 11, 0.28)",  // amber-500
      "rgba(249, 115, 22, 0.22)",  // orange-500
      "rgba(253, 224, 71, 0.22)",  // yellow-300
    ],
    emoji: "👑"
  }
};

export const AURORA_SPEEDS = {
  static: { id: 'static' as const, name: "Static", seconds: 0, nodeSpeedMultiplier: 0 },
  slow: { id: 'slow' as const, name: "Slow", seconds: 45, nodeSpeedMultiplier: 0.5 },
  normal: { id: 'normal' as const, name: "Normal", seconds: 22, nodeSpeedMultiplier: 1 },
  fast: { id: 'fast' as const, name: "Fast", seconds: 12, nodeSpeedMultiplier: 1.8 },
  ultra_fast: { id: 'ultra_fast' as const, name: "Ultra-Fast", seconds: 5, nodeSpeedMultiplier: 3.5 }
};

